version: "3.7"

services:
    donny-t:
        image: kruhlmann/donny-t:onbuild
        container_name: donny-t
        restart: unless-stopped
        command: sh -c "ruby -Ilib /usr/app/bin/donny-t -d discord_key -b twitter_bearer_token -s twitter_secret -t twitter_key
